### ISSUE TITLE
Browser Preview extension have problem that endless create new tab, but core project no this problem.

### ISSUE THREAD

**Issue by xyj404** [opensumi/ide-startup#10]
![image](https://user-images.githubusercontent.com/17355263/159444227-9ded0977-cc2a-459c-b7b1-1509d8cb0741.png)

**Comment by erha19** [comment]
@xyj404 更新完代码，这个问题还存在吗？

**Comment by xyj404** [comment]
@erha19  是的

**Comment by xyj404** [comment]
@erha19  这个Browser Preview，想用这个浏览打包，热更新后的代码。
![image](https://user-images.githubusercontent.com/17355263/159464007-59346182-2428-4a99-a7a4-358763417050.png)

**Comment by erha19** [comment]
@xyj404 试了一下这个问题应该是框架实现上的 Bug，部分消息响应出现了循环的情况，我们这边跟进修复一下

**Comment by erha19** [comment]
将会在 core 中修复该问题

- https://github.com/opensumi/core/issues/723

**Comment by xyj404** [comment]
感谢，core修复了，ide-startup是不是就可以了

**Comment by erha19** [comment]
> 感谢，core修复了，ide-startup是不是就可以了

到时候 `ide-startup` 中可以通过更新依赖版本解决

**Comment by erha19** [comment]
已修复 https://github.com/opensumi/core/pull/1262.
