### ISSUE TITLE
git clone的代码库无法被源代码管理模块识别

### ISSUE THREAD

**Issue by zlweicoder** [opensumi/ide-startup#12]
![image](https://user-images.githubusercontent.com/13825714/160543283-bf4f3675-4bae-4413-97a5-16018b83038b.png)

**Comment by zlweicoder** [comment]
1.
![image](https://user-images.githubusercontent.com/13825714/160579762-78ce817a-7dc4-4e09-a8ae-688778944be1.png)
2.
![image](https://user-images.githubusercontent.com/13825714/160580079-6d406289-bd78-449b-8038-e34687d9b78c.png)
3.
![image](https://user-images.githubusercontent.com/13825714/160580204-50bd37f6-ec7b-40ce-8b59-6d775ecd2c9d.png)
4.
![image](https://user-images.githubusercontent.com/13825714/160580266-94e2ab0b-4bfc-4203-97b3-e7919d47bb38.png)

**Comment by zlweicoder** [comment]
![image](https://user-images.githubusercontent.com/13825714/160580628-e7a916d5-8ac0-406f-b933-f7f8e39af8b9.png)
安装完毕这俩插件后恢复正常了，源代码管理可用了。

**Comment by Aaaaash** [comment]
👌🏻
