### ISSUE TITLE
[feature request] support arm64 platform

### ISSUE THREAD

**Issue by songhn233** [opensumi/ide-startup#14]
> The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

```
docker manifest inspect ghcr.io/opensumi/opensumi-web
```
The manifest does not support multi-cpu architecture, therefore mac with Apple silicon does not work properly and needs to be built by buildx etc.

**Comment by Aaaaash** [comment]
You can try the new ARM64 image

> docker pull ghcr.io/opensumi/opensumi-web:master@sha256:b35b4900d3eda457cc2cad4e409760555d409a0678374bf079aefc4916f3352a
