### ISSUE TITLE
docker构建异常

### ISSUE THREAD

**Issue by relife957** [opensumi/ide-startup#16]
构建过程
1. 直接使用项目自带的dockerfile构建，异常如下
![image](https://user-images.githubusercontent.com/27293981/168979986-0905f670-9888-4458-a448-c7dd59785246.png)
2. 指定两个依赖库版本后
`"vscode-languageserver-protocol": "3.16.0",
    "vscode-jsonrpc": "6.0.0"`
异常如下
<img width="1174" alt="截屏2022-05-18 15 18 37" src="https://user-images.githubusercontent.com/27293981/168980345-605bba1f-2c1a-4f7c-814e-766fbec72659.png">. 
异常日志详情
<img width="1475" alt="截屏2022-05-18 15 20 14" src="https://user-images.githubusercontent.com/27293981/168980657-84742313-b169-48c0-b30e-a6bc94da874b.png">

**Comment by Aaaaash** [comment]
fixed

**Comment by relife957** [comment]
根本原因是本地docker配置不足导致，最少需要4g内存
