### ISSUE TITLE
postinstall error 

### ISSUE THREAD

**Issue by cfxmj2014** [opensumi/ide-startup#23]
<img width="633" alt="image" src="https://user-images.githubusercontent.com/10257543/175441382-c9cb6b9e-a7e4-495d-859d-caa4ee0a2490.png">

**Comment by cfxmj2014** [comment]
compile:node error too....
<img width="639" alt="image" src="https://user-images.githubusercontent.com/10257543/175441589-c868d7b4-f7e6-4944-8d3f-b92872fe32c1.png">

**Comment by bytemain** [comment]
fixed in #22

**Comment by cfxmj2014** [comment]
postinstall ok了，compile:node还是报错

**Comment by cfxmj2014** [comment]
依赖问题，重新yarn就行了
