### ISSUE TITLE
server怎么部署？

### ISSUE THREAD

**Issue by cfxmj2014** [opensumi/ide-startup#24]
server怎么部署？直接部署dist-node报错

**Comment by cfxmj2014** [comment]
？？？

**Comment by Aaaaash** [comment]
你好，请提供详细的上下文，比如是如何“部署”的，"直接部署 dist-node 报错" 是指在什么情况下做了什么操作后出现了什么样的错误。

**Comment by cfxmj2014** [comment]
web ide怎么部署，除了部署打包后的静态资源dist以外，需要的ws服务怎么部署？我是直接部署的dist-node，看起来是不行，没使用docker

**Comment by Aaaaash** [comment]
我的问题是
> 直接部署的dist-node，看起来是不行 
是指怎么样部署的？copy 文件到服务器上？
`dist-node` 里是打包好的 Node.js 服务，可以直接用 node 来运行，放在服务器上可以使用 pm2  这类工具来管理

**Comment by cfxmj2014** [comment]
对，我就是用pm2起的，看了下缺少nsfw一些依赖，我看了下dockerfile，还需要productionDependencies里面的5个依赖，这个打包的时候没有放进去，需要手动去操作吗？

**Comment by Aaaaash** [comment]
Dockerfile 里会把这几个依赖单独安装，如果自己部署的话也需要类似的操作，具体来说就是把这几个依赖装到部署 dist-node 的那个目录下

**Comment by cfxmj2014** [comment]
为啥不放在package里面，单独拿出来呢？

**Comment by Aaaaash** [comment]
为了减小镜像体积，打包后实际运行时只依赖 productionDependencies 里的几个 Node Addons, 如果不单独拿出来也要删掉其他依赖只保留这几个，相比之下用一个单独的 package.json 安装更简单

**Comment by cfxmj2014** [comment]
我还是用docker管理吧，分开打包有点麻烦，谢谢解答。
