### ISSUE TITLE
AppConfig.staticServicePath 配置不生效

### ISSUE THREAD

**Issue by relife957** [opensumi/ide-startup#25]
## 背景
我的场景需要在域名后面加一个路径path来携带一些信息，例如 http://domain/path 来打开主页

## 问题
针对ws，可以配置AppConfig.wsPath 来配置，可以生效
针对静态文件，我使用AppConfig.staticServicePath 来配置，但是未生效
预期 ： http://domain/**path**/assets/root/.sumi/extensions/vscode-icons-team.vscode-icons/icons/folder_type_src.svg,
实际 ： http://domain/assets/root/.sumi/extensions/vscode-icons-team.vscode-icons/icons/folder_type_src.svg,

无法携带path信息

**Comment by relife957** [comment]
node ： 16.x
opensumi：2.17.5

**Comment by erha19** [comment]
@relife957 已修复，预计会在 2.19.0 版本发布
