### ISSUE TITLE
web ide部署以后，有什么方式可以open本地的workspace？

### ISSUE THREAD

**Issue by cfxmj2014** [opensumi/ide-startup#27]

**Comment by erha19** [comment]
@cfxmj2014 在 `ide-startup` 项目里面问吗写了个简单的例子，你可以通过修改 URL 参数来打开本地 workspace ，代码见 [render-app.ts#L17](https://github.com/opensumi/ide-startup/blob/aa9b9d67d489bd8c0825a1f53e6ba2c4c88884cd/src/browser/render-app.ts#L17) ,  例如 :`http://localhost:8080?workspaceDir=xxxx`.

**Comment by cfxmj2014** [comment]
我已经部署到服务器了，想要open本地的workspace，比如可以打开本地文件夹，要不然web ide的workspaceDir可以打开远程的git仓库？类似https://github.dev/github/dev

**Comment by cfxmj2014** [comment]
@erha19 辛苦解答下

**Comment by erha19** [comment]
> 我已经部署到服务器了，想要open本地的workspace，比如可以打开本地文件夹，要不然web ide的workspaceDir可以打开远程的git仓库？类似https://github.dev/github/dev

@cfxmj2014  IDE-Startup 只是一个简单的实例项目，你可以通过启动时传入 `workspaceDir` 配置来定义打开的本地文件夹，当前也不支持打开远程 git 仓库，需要你自行实现业务逻辑

**Comment by cfxmj2014** [comment]
@erha19 可能我没表述清楚哈，比如web ide是一个远端服务，不同用户访问ide，肯定是希望用这个web ide打开本地的文件进行开发吧，这个需要我们来实现类似showDirectoryPicker来打开本地文件夹，然后把文件内容再传给web ide的workspace来实现吗？

**Comment by cfxmj2014** [comment]
@erha19 类似https://vscode.dev/ 这个打开文件夹功能，这个需要自己集成？
![image](https://user-images.githubusercontent.com/10257543/176833245-ebb7002d-b386-4ab6-9f4f-3915ab308ce6.png)

**Comment by erha19** [comment]
@cfxmj2014 目前该功能我们默认只在 Electron 中支持，由于 Web 环境下存在多种情况，没有默认实现，你可以自行实现，通过上层控制或 URL 拼接均可。

**Comment by cfxmj2014** [comment]
URL 拼接是指？workspaceDir？workspaceDir拼接本地的dir不行啊

**Comment by erha19** [comment]
@cfxmj2014 看上面这段 https://github.com/opensumi/ide-startup/issues/27#issuecomment-1171841514

**Comment by cfxmj2014** [comment]
本地起服务是可以，我的意思是部署在服务器了，workspaceDir参数是用户本地的文件夹，肯定找不到path啊。。。文件系统都不是一个，是我理解的问题吗

**Comment by erha19** [comment]
> 本地起服务是可以，我的意思是部署在服务器了，workspaceDir参数是用户本地的文件夹，肯定找不到path啊。。。文件系统都不是一个，是我理解的问题吗

如果是希望做 https://vscode.dev/  类似的效果，需要去用到 Chrome 的 FileSystem API 去实现，用纯前端项目去做，可以参考一下纯前端的案例 https://opensumi.com/zh/docs/integrate/quick-start/lite，目前对接的是 GitHub API
