### ISSUE TITLE
通过 dist-node 启动后，Git 模块无效

### ISSUE THREAD

**Issue by icarusion** [opensumi/ide-startup#31]
使用 `npm start` 启动，一切正常，但是 build 后，通过 `node dist-node/server/index.js` 启动，Git 模块就无效，部分插件也无效（这里安装的 Vue，在 npm start 里都正常）

**在本地和 centos 上均存在相同问题**

以下是截图：

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/5370542/179184320-66d5a7a4-61ba-47bd-a2b3-66826e622485.png">

<img width="365" alt="image" src="https://user-images.githubusercontent.com/5370542/179184395-6fdc168c-d4b1-41e3-87ad-4d2f5138cb60.png">

<img width="357" alt="image" src="https://user-images.githubusercontent.com/5370542/179184441-d475891c-5972-420c-97b9-07138e8502f3.png">

<img width="365" alt="image" src="https://user-images.githubusercontent.com/5370542/179184499-a782547a-0b35-47d9-aa5e-cb8ed59d56ab.png">

![image](https://user-images.githubusercontent.com/5370542/179184721-51bc860b-4669-4820-8ccb-8001731a0d7e.png)

**Comment by erha19** [comment]
@icarusion 这里的原因主要是默认的插件进程文件无法正确拼接为正确的路径，`appConfig. extHost` 读取到了不正确的路径，同时 module.filename 
 无法正确读取也导致了该问题

https://github.com/opensumi/core/blob/060ffcb490229c8ff1d0e3b591d67fe952670b58/packages/extension/src/node/extension.service.ts#L321

你重新 pull 一下最新代码，已在 #32 中修复

**Comment by icarusion** [comment]
收到，我试一下，谢谢

**Comment by erha19** [comment]
@icarusion 可以再试一下，刚刚提交了一点新代码

**Comment by icarusion** [comment]
Git 模块还是不行，然后有一个新的报错，我本地并没有 `/hosted/ext.host.js`，里面只有一个 `/hosted/ext.process.js`
<img width="894" alt="image" src="https://user-images.githubusercontent.com/5370542/179207142-812d56c8-3521-4cd3-baba-8af60eda3608.png">

**Comment by icarusion** [comment]
可以了，谢谢
