### ISSUE TITLE
尝试设置extensionCandidate参数，似乎没有生效

### ISSUE THREAD

**Issue by hjue** [opensumi/ide-startup#36]
我在index.ts 中设置了extensionCandidate和extensionDir，yarn start后已安装的插件显示我预置的插件（如下图），这个是我期望的。
但extensionCandidate指定的插件未加载,这点可以从 Show Running Extensions中观察到，同时 html 未高亮也证实系统预置插件未加载。

![image](https://user-images.githubusercontent.com/1135045/180357680-b1f6a47e-2481-499c-9275-ce2e8e06ef72.png)

这是我修改的index.ts 代码
```
renderApp({
  extensionDir: "/xxx/ide-startup/my-extensions",
  extensionCandidate: [{
    path: '/xxx/ide-startup/extensions',
    isBuiltin: true,
    isDevelopment: false
  }],
  modules: [
    ...CommonBrowserModules,
    ExpressFileServerModule,
  ],
```

**Comment by erha19** [comment]
@hjue 这里你的参数内容写错了, `extensionCandidate ` 传入的应该为具体的插件路径，而非插件的父目录，如
```ts
extensionCandidate: [{
    path: '/xxx/ide-startup/extensions/vscode-extensions.html',
    isBuiltin: true,
    isDevelopment: false
}]
```
