### ISSUE TITLE
build 后，node dist-node/server/index.js 报错

### ISSUE THREAD

**Issue by icarusion** [opensumi/ide-startup#38]
理论上，`npm run build` 之后，只需要部署 `dist`、`dist-node`、`hosted` 三个目录即可启动服务，但目前报错：

<img width="642" alt="image" src="https://user-images.githubusercontent.com/5370542/180919652-b6c41238-d91e-40de-865d-f0336ccd56f7.png">

但如果把 `node_modules` 目录也放上，是可以启动 `8000` 的。

**Comment by Aaaaash** [comment]
需要保留 node_modules 中的 native 模块，可以参考 Dockerfile 中的脚本，把 [productionDependencies.json](https://github.com/opensumi/ide-startup/blob/master/configs/docker/productionDependencies.json) 里的依赖构建后单独安装一次
https://github.com/opensumi/ide-startup/blob/master/Dockerfile#L31-L34

**Comment by icarusion** [comment]
好的 谢谢
