### ISSUE TITLE
web版使用git插件clone无法下载代码

### ISSUE THREAD

**Issue by renzl321** [opensumi/ide-startup#40]
1、在web版中安装git插件
2、选择源码管理git 的clone
3、在打开的地址中输入仓库地址回车无效
![lQLPJxaityPKU0rNAaPNBJWwwt8BQqD3vLkDC6jBlgBUAA_1173_419](https://user-images.githubusercontent.com/30283157/187149390-d08e20ad-4589-4623-8368-cdcc01f71df1.png)

**Comment by erha19** [comment]
@renzl321 该功能在 Web 版本下是不支持的，Git 功能的实现与插件相关。
