### ISSUE TITLE
打开目录按钮控制台报错

### ISSUE THREAD

**Issue by 15083055793** [opensumi/ide-startup#44]
Uncaught (in promise) HANDLER_NOT_FOUND: The command 'filetree.open.folder' cannot be executed. There are no active handlers available for the command.

**Comment by erha19** [comment]
@15083055793 目前这块功能需要你自行实现，见：https://github.com/opensumi/core/issues/1574#issuecomment-1226707609 ，后面我做一下例子在 [opensumi/ide-startup](https://github.com/opensumi/ide-startup) 实现一下简单案例好了

**Comment by erha19** [comment]
@15083055793 可以参考一下 https://github.com/opensumi/ide-startup/pull/45
