### ISSUE TITLE
Docker镜像版本跟上好吗

### ISSUE THREAD

**Issue by alyenc** [opensumi/ide-startup#49]
Docker镜像版本跟上好吗？5个月前带着各种bug的版本没人管了吗？

**Comment by erha19** [comment]
@alyenc  ide-startup 仅为示例性质项目，主要展示如何集成并使用 OpenSumi 版本，并不保证其能直接使用于生产环境，如有需要都是可以自行打包或升级依赖版本。

稍晚一会会升级一下 Docker 镜像依赖版本。
