### ISSUE TITLE
只能本地访问吗？

### ISSUE THREAD

**Issue by hrz0828** [opensumi/ide-startup#5]
怎么改配置文件

**Comment by Aaaaash** [comment]
我理解你的意思是只能通过本地 127.0.0.1 来访问？
这个其实是不限制的，这个项目是一个 Cloude IDE 的完整实例，如果你是个人使用，可以在任何云服务器上部署，然后绑定域名来使用。
如果是面向多人提供 Cloud IDE 服务的话，还需要类似 K8s 之类的技术搭建一套容器集群来管理容器实例。

**Comment by xiaojia21190** [comment]
docker 打开后页面空白

**Comment by Aaaaash** [comment]
> docker 打开后页面空白

提供一下详细的错误信息，比如浏览器 devtools 的报错

**Comment by AEPKILL** [comment]
我是本地打开，也是空白，没有任何报错

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/9626630/156994020-5819815d-825c-4e78-81c0-ea33aee755a4.png">

**Comment by Aaaaash** [comment]
按照 README.md 的步骤来，打开 `http://127.0.0.1:8080`, 8899 端口是依赖的其他服务
