### ISSUE TITLE
如何离线部署

### ISSUE THREAD

**Issue by lyonxh** [opensumi/ide-startup#62]

**Comment by hacke2** [comment]
@Ricbet 有离线部署的经验，沉淀一个文档吧

**Comment by lyonxh** [comment]
> @Ricbet 有离线部署的经验，沉淀一个文档吧

是不是要从docker导镜像啊

**Comment by Ricbet** [comment]
@lyonxh 不需要，要离线部署的话只需要将 OpenSumi 里一些需要外网获取的资源给配置成内网资源就行，晚点我补充一份文档给你参考下需要配置哪些资源

**Comment by lyonxh** [comment]
> 

感谢大佬

**Comment by Ricbet** [comment]
@lyonxh 你先看一下这个文档示例 https://github.com/opensumi/docs/pull/99/files?short_path=d703d81#diff-d703d81fe47542c8634f8536595a302850e9c14d7cb8787623a33e6cdf8e6cd5

**Comment by lyonxh** [comment]
@Ricbet 部署完域名在哪改啊

**Comment by Ricbet** [comment]
> @Ricbet 部署完域名在哪改啊

什么域名？

**Comment by Ricbet** [comment]
> @Ricbet 大佬 扩展有办法离线安装吗

你可以提前把扩展下载好，然后放在插件目录里，插件目录是由你设置的 extensionDir 配置

[custom-config](https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-config)

**Comment by lyonxh** [comment]
@Ricbet 扩展包我放进去了 可是 包里面的插件要怎么升级呢  比如我下的是go包

**Comment by lyonxh** [comment]
我自己试试手动安装吧

**Comment by Ricbet** [comment]
> @Ricbet 扩展包我放进去了 可是 包里面的插件要怎么升级呢 比如我下的是go包

没办法升级，因为插件下载是需要有插件市场的，就需要联接外网，你这种情况只能是先下载好新的插件包再做替换

**Comment by lyonxh** [comment]
@Ricbet 我把那些工具二进制包放在文件夹里了 但是感觉程序并没有加载 一直提示安装插件 代码现在可以在命令行用命令运行
