### ISSUE TITLE
文件目录 文件夹有时候会跑到上面去一点点 不知道是bug还是什么

### ISSUE THREAD

**Issue by lyonxh** [opensumi/ide-startup#63]
<img width="380" alt="WeChat9d0dd41dae48916b94c147cb2928a441" src="https://user-images.githubusercontent.com/77234741/229794292-21c72c9a-af58-4a7e-b53f-4d8e14ba64c6.png">

**Comment by erha19** [comment]
@lyonxh 提供一下复现的录屏或过程（以及 OpenSumi 版本信息，运行环境），这个应该是视图渲染上的问题，另外看一下运行的控制台是否有相关报错信息。
