### ISSUE TITLE
插件异常

### ISSUE THREAD

**Issue by dwqdaiwenqi** [opensumi/ide-startup#67]
本地运行 `yarn start`，进入页面，是正确的，存在主题插件，如图：
<img width="1146" alt="image" src="https://github.com/opensumi/ide-startup/assets/18524392/0cbebb14-370e-4356-b200-a14b585cdbc8">

运行打包命令`yarn build`，再启动node服务` node dist-node/server/index.js `，进入页面后，就没有主题插件了，如图：
<img width="1628" alt="image" src="https://github.com/opensumi/ide-startup/assets/18524392/19d3d173-b8d7-456a-a235-4c376d6184d6">

并且node服务报错：
<img width="1066" alt="image" src="https://github.com/opensumi/ide-startup/assets/18524392/0b54573b-0cdc-430c-a6ba-ac5ee553bd8c">

 这是为什么，怎么解决呢？

**Comment by erha19** [comment]
@dwqdaiwenqi 关于插件 DIR 配置，可以看一下这个文档 [自定义配置](https://opensumi.com/zh/docs/integrate/universal-integrate-case/custom-config#%E6%B5%8F%E8%A7%88%E5%99%A8%E7%AB%AF%E9%85%8D%E7%BD%AE)

对于 WebIDE 环境的生产环境部署脚本，你这边可以参考一下我们写的 Docker 示例的写法：

https://github.com/opensumi/ide-startup/blob/492a6c222f8a04b00997f8f42ef26a117fefb6ae/Dockerfile#L14-L40
