### ISSUE TITLE
No intelliSense in any language at this project but core project have.

### ISSUE THREAD

**Issue by xyj404** [opensumi/ide-startup#7]

**Comment by Aaaaash** [comment]
You need run `npm run download:extensions` command first.

**Comment by xyj404** [comment]
I try it. but get errors:
![image](https://user-images.githubusercontent.com/17355263/159202201-9cec34b1-4ad5-4c3c-8a2f-15b0257c3b4d.png)

**Comment by xyj404** [comment]
I don't why but it success when I try several times. Thanks your help! @Aaaaash
