### ISSUE TITLE
我在renderApp已经设置了isElectronRenderer: false，ReferenceError: ElectronIpcRenderer is not defined

### ISSUE THREAD

**Issue by dongodngtang** [opensumi/ide-startup#70]
我打包后启动的服务，在electron中使用iframe加载出现以下错误

ReferenceError: ElectronIpcRenderer is not defined
    at Proxy.on (bundle.js:2)
    at bundle.js:2
    at ua (bundle.js:2)
    at Al (bundle.js:2)
    at t.unstable_runWithPriority (bundle.js:2)
    at qr (bundle.js:2)
    at Rl (bundle.js:2)
    at bundle.js:2
    at j (bundle.js:2)
    at MessagePort.w.port1.onmessage (bundle.js:2)

我在renderApp已经设置了isElectronRenderer: false。这是哪里还有判断呀！浏览器运行是正常的

**Comment by dongodngtang** [comment]
我定义了一个前后端服务出现了以上问题。export class MavenService extends RPCService implements IMavenService {

**Comment by bytemain** [comment]
是什么版本的 OpenSumi？

**Comment by dongodngtang** [comment]
> 
2.22.5

**Comment by bytemain** [comment]
升级到 2.22.6 及以上再试下，我们最新版本已经 2.25.x 了。

修复：
- https://github.com/opensumi/core/pull/2366

**Comment by dongodngtang** [comment]
> ，我们最新

好的

**Comment by dongodngtang** [comment]
> 升级到 2.22.6 及以上再试下，我们最新版本已经 2.25.x 了。
> 
> 修复：
> 
> * [fix: deprecated isElectronRenderer and use appConfig.isElectronRenderer core#2366](https://github.com/opensumi/core/pull/2366)

升级版本后，问题已解决，谢谢！！！
