### ISSUE TITLE
yarn start error

### ISSUE THREAD

**Issue by kkzzyut0** [opensumi/ide-startup#72]
![image](https://github.com/opensumi/ide-startup/assets/126401141/edee50a6-87df-4932-8301-d3a3d7cb5215)
I followed the steps in quick start, but it doesn't work.

**Comment by erha19** [comment]
@kkzzyut0 可以参考 #73 修改一下本地项目尝试一下

**Comment by freemanxzx** [comment]
这样似乎解决不了，仍然报错

**Comment by erha19** [comment]
> 这样似乎解决不了，仍然报错

@freemanxzx 有点久远了，试试最新的分支代码，移除 node_modules 后重新运行一下

**Comment by freemanxzx** [comment]
今天早上拉的main里的代码，我看了下tsconfig.json格式是对的，但包的错是一样的，反复yarn cache clean --force 以及rimraf node_nodes都不行

**Comment by freemanxzx** [comment]
新建#102 了， 帮忙看看是啥原因 @erha19
