### ISSUE TITLE
文件持续加载，无法结束

### ISSUE THREAD

**Issue by Hitooooo** [opensumi/ide-startup#74]
![image](https://github.com/opensumi/ide-startup/assets/19512047/c3d1b50f-7a91-40e9-bf6f-68b493ecdbb3)
不知道某些情况会触发，一直卡在加载文件，无法显示已保存文件

容器内查看报错：
![image](https://github.com/opensumi/ide-startup/assets/19512047/1fa2ce00-bf31-4e0a-adf0-1e7108b68fdc)

不确定该报错是否导致文件加载问题

**Comment by Hitooooo** [comment]
未安装python、python-basic插件是正常的，安装后刷新重新进入后，无法加载文件

**Comment by erha19** [comment]
@Hitooooo 可以试一下目前蚂蚁插件市场 https://marketplace.opentrs.cn/square 同步的版本，Python 相关插件跟内核的版本对应关系较为复杂，直接下载可能无法使用。
