### ISSUE TITLE
Extension market no content and live preview extension can't use after install.

### ISSUE THREAD

**Issue by xyj404** [opensumi/ide-startup#8]
![image](https://user-images.githubusercontent.com/17355263/159399556-92d00bb5-ba17-43cc-a9e6-d93564cecbbd.png)

**Comment by xyj404** [comment]
And core project is ok.

**Comment by erha19** [comment]
@xyj404 试一下使用 `http://0.0.0.0:8080` 访问，主要是访问跨域问题

**Comment by xyj404** [comment]
@erha19  还是不行

**Comment by erha19** [comment]
@xyj404 pull 一下最新的 master 代码

**Comment by xyj404** [comment]
nice 现在好了! @erha19
